spring:
  profiles:
    active: dev
mybatis-plus:
  configuration: # 支持mybatis的原生的配置，就是既可以写sql也可以调用封装好方法来执行增删改查
    map-underscore-to-camel-case: true # 是否开启驼峰命名规则，默认是false
    auto-mapping-behavior: full # 配置自动映射策略，让mybatis来自动把数据库自动映射对应的实体
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印sql语句，日志
  mapper-locations: classpath*:**.mapper/*Mapper.xml #指定mybatis的xml文件位置 classpath*不仅包含class路径，还包括jar文件中（class路径）进行查找
